# netlify.toml

[build]
  functions = "functions"  # Directorio donde se encuentran las funciones serverless

[functions.api_alumnos]
  path = "api/alumnos"   # Ruta relativa de la función serverless
  memory = 128           # Opcional: límite de memoria en MB
  timeout = 10           # Opcional: tiempo máximo de ejecución en segundos
